mappings:
  HoneypotSpamProtector: StudioBonito\SpamProtectionHoneypot\SpamProtector\HoneypotSpamProtector
  HoneypotField: StudioBonito\SpamProtectionHoneypot\FormField\HoneypotField
  HoneypotFieldTest: StudioBonito\SpamProtectionHoneypot\Tests\HoneypotFieldTest
